### ISSUE TITLE
Special-case the `_bulk` endpoint

### ISSUE THREAD

**Issue by dakrone** [dakrone/es-mode#21]
It'd be great if we could special-case the `/_bulk` and `/{index}/{type}/_bulk` endpoints so es-mode could load things with bulk insert there, it will rely on parsing multiple JSON objects for a single headline.

**Comment by chenl** [comment]
It is almost a year since this issue was created. Any thoughts about it?

**Comment by dakrone** [comment]
@chenl I still need to do it! (or have someone submit a PR), I haven't forgotten about it though :)

**Comment by dakrone** [comment]
@chenl I pushed changes for this, please try it out and let me know if you find any problems!
