### ISSUE TITLE
es-goto-next-request should return t I believe

### ISSUE THREAD

**Issue by ahungry** [dakrone/es-mode#24]
For the prefix mode of es-execute-request-dwim, it doesn't seem to iterate in the while loop, unless es-goto-next-request returns t (true) as the final evaluation.

Updating as such causes the program to work as expected (although I'm not a fan of it making a new buffer for each request in this case, vs just sharing the same buffer and appending output)

**Comment by dakrone** [comment]
@ahungry thanks for bringing this up, I might have just broken this with my push from yesterday, I'll take a look.

Really, I need to add tests for this :)

**Comment by dakrone** [comment]
@ahungry I pushed a new commit for this, can you check it out and see if it's working for you? (I tested locally and it seems to work for me)

**Comment by ahungry** [comment]
it works!

**Comment by dakrone** [comment]
Awesome, I will close this then, thanks for reporting!
