### ISSUE TITLE
Wouldn't it be nice es-result-mode supports hs-minor-mode?

### ISSUE THREAD

**Issue by i12o** [dakrone/es-mode#27]
Most of result JSON are tooo loooong.

It would be very nice, if I can toggle fold/unfold of subtree.

So I wrote something into my .emacs.  To be able to toggle hs-minor-mode under
es-result-mode. To use hs-minor-mode, requirements seems:

1. hs-special-mode-alist holds entry for es-result-mode
1. es-result-mode buffer must have comment-start and comment-end variable set.

`(add-to-list 'hs-special-modes-alist '(es-result-mode "{" "}" "/[*/]" nil))`

`(add-hook 'es-result-mode-hook
          (lambda ()
            (setq-local comment-start "// ")
            (setq-local comment-end "" )
            (hs-minor-mode 1)
            (local-set-key (kbd "C-c C-=") 'hs-toggle-hiding)
            ))
`

**Comment by dakrone** [comment]
I totally agree enabling hs-minor-mode would be very nice! I can probably look at adding es-result-mode to the `hs-special-modes-alist` and configuring it appropriately, great idea!

**Comment by dakrone** [comment]
@i12o I pushed a really simple commit for this, the other part though, looks like something that could go in the `es-result-mode-hook`, as you said, so I'm not sure if we should force hs-minor-mode on everyone, would you by interested in opening a PR to add how to set this up to the README?
