### ISSUE TITLE
basic authentication support

### ISSUE THREAD

**Issue by hamelg** [dakrone/es-mode#31]
Hello,
Our es cluster is protected by http basic authentication. When es-mode is trying to connect it, we get this error : 

`
Contacting host: my_escluster:443
url-http-parse-headers: Wrong type argument: char-or-string-p, nil
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  url-http-handle-authentication(nil)
  url-http-parse-headers()
  url-http-chunked-encoding-after-change-function(296 406 110)
  url-http-wait-for-headers-change-function(1 418 417)
  url-http-generic-filter(#<process my_escluster...
`

It would be nice to support http basic auth scheme.
thank you much for es-mode, it is very useful.

**Comment by hamelg** [comment]
Sorry.
Basic auth works perfectly. My issue came from incorrect http setup.

**Comment by dakrone** [comment]
Cool, glad you figured it out, glad you find it useful!

**Comment by littlehome-eugene** [comment]
I'm trying `https://username:password@example.com` as ES url, but it doesn't work.. 

Maybe because it's self signed certificate.. Is there a way to skip certificate validation?

**Comment by littlehome-eugene** [comment]
I had to do this https://github.com/millejoh/emacs-ipython-notebook/wiki/Tips 

inserting `-k` option to allow self-signed certificate
