### ISSUE TITLE
Formatting problems with tablify

### ISSUE THREAD

**Issue by cbaines** [dakrone/es-mode#34]
Thanks for writing this, I'm really excited about using it :)

I'm having problems with the formatting of the tablify output. I'm getting \n in the outputs, when I probably should be getting newlines.

```
#+BEGIN_SRC es :tablify application :results raw table
POST http://localhost:9200/logs-2016.09.09,logs-2016.09.08,logs-2016.09.07/_search
{
  "aggs" : {
    "application" : {
      "terms" : {
        "field" : "application",
        "size" : 2
      }
    }
  },
  "size": 0
}
#+END_SRC

#+RESULTS:
| key | document count \n | --+-- | \n | foo | 5903896 \n | bar | 4467594 |
```

**Comment by dakrone** [comment]
Strange! Okay, I'll look into it!

What version of Org-mode and Emacs are you using?

**Comment by cbaines** [comment]
I was using emacs 24.5 (through GNU Guix), and was using the included version of Org. But, just installing the emacs-org package (version 20160815) has fixed the issue.

So I guess there are some issues with older versions of Org, but at least I have things working now :)

**Comment by dakrone** [comment]
I haven't been able to reproduce this, so I'm going to close for now as org-mode version weirdness, if you see it again feel free to re-open!
