### ISSUE TITLE
es-cc missing dependency on s.el package

### ISSUE THREAD

**Issue by tk-saj** [dakrone/es-mode#38]
I was trying to run es-command-center on a new Emacs installation and es-command-center would not start due to a void s-ends-with-p function.

I'm sure s.el is fairly ubiquitous (I forgot it wasn't builtin), but it needs to be brought in with the package installation of es-mode.

Once I got 's' installed on the new Emacs, all is well.

PS
Nice bit of programming btw - es-mode is quite handy.

**Comment by dakrone** [comment]
Whoops thanks! I'll fix that right now.

> Nice bit of programming btw - es-mode is quite handy.

Thanks, I'm glad it's useful!
