### ISSUE TITLE
Auto-format response JSON after es-execute-request-dwim

### ISSUE THREAD

**Issue by RichardW42** [dakrone/es-mode#67]
The result of C-c C-c is a one-line json which is not easy to read.

Is there a way to auto-format response json? I tried with json-mode, but the response buffer is read_only. I noticed there's a es-response-success-functions hook, but I'am new to lisp and didn't find a clue to use it format response. Any help would be appreciate.

**Comment by dakrone** [comment]
You can set `es-always-pretty-print` to `t` and the output will automatically be formatted.
