### ISSUE TITLE
es-control-centre doesn't quit properly

### ISSUE THREAD

**Issue by ilyaguy** [dakrone/es-mode#68]
ES Control Centre doesn't quit properly. It leaves the requesting process which tries to update deleted buffer. Also it has a problems if elastic server doesn't respond due to closing VPN or changing network.

**Comment by dakrone** [comment]
Hi @ilyaguy, can you see if the merged change in #69 fixed this?

**Comment by ilyaguy** [comment]
hi @dakrone, the issue has been fixed. Thank you.

**Comment by dakrone** [comment]
Great glad to hear it!
