### ISSUE TITLE
[Q] How to create elasticsearch indices for a directory of org-mode files?

### ISSUE THREAD

**Issue by NightMachinary** [dakrone/es-mode#81]
Prescript: Sorry to bother you.

I like to use elasticsearch to do full-text searches on my org-files. I have taken a look at the documentation of elasticsearch, but the docs are rather daunting and seem to be focused on solving big business problems. I wonder if you know of a guide to setup a simple full-text search on org-mode (plain-text) files for personal use, with readymade frontends.

For example, I like to have a web full-text search UI for https://github.com/NightMachinary/r_rational .

**Comment by dakrone** [comment]
Hi @NightMachinary, not a bother at all.

If you have a bunch of text files you want to index, I would recommend checking into something like Logstash (https://github.com/elastic/logstash) or filebeat (https://www.elastic.co/beats/filebeat). You might want something that can parse them out a bit though, into different headlines or subsections. For something like that, you'd need to use a REST client for Elasticsearch (there are many in different languages)

**Comment by NightMachinary** [comment]
Thanks! I'll look into them.
